# Generated by Django 5.1.2 on 2024-10-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='created_on',
            new_name='updated_at',
        ),
    ]
