# Generated by Django 5.1.2 on 2024-10-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_created_on_movie_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='film_type',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default='N/A', max_length=4),
            preserve_default=False,
        ),
    ]
