# Generated by Django 5.1.2 on 2024-10-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_film_type_movie_poster_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='film_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
