# Generated by Django 5.1.2 on 2024-10-14 16:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0'), message='Rating must be between 1.0 and 5.0'), django.core.validators.MaxValueValidator(Decimal('5.0'), message='Rating must be between 1.0 and 5.0')]),
        ),
    ]
